"""initial schema

Revision ID: 06a8ced04527
Revises:
Create Date: 2026-10-05 17:07:06.899484

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import coinwatch.db.base

# revision identifiers, used by Alembic.
revision: str = "06a8ced04527"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", coinwatch.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=False),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=False),
        sa.Column("after_json", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_table(
        "chains",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("native_symbol", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chains")),
    )
    op.execute(sa.text("INSERT INTO chains (id, native_symbol) VALUES ('solana', 'SOL')"))
    op.create_table(
        "digests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", coinwatch.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("sent_at", coinwatch.db.base.UtcDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_digests")),
    )
    op.create_table(
        "inference_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("ts", coinwatch.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inference_calls")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("disabled_at", coinwatch.db.base.UtcDateTime(timezone=True), nullable=True),
        sa.Column("created_at", coinwatch.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "coins",
        sa.Column("chain", sa.String(length=32), nullable=False),
        sa.Column("address", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("created_at", coinwatch.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("graduated_at", coinwatch.db.base.UtcDateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["chain"], ["chains.id"], name=op.f("fk_coins_chain_chains")),
        sa.PrimaryKeyConstraint("chain", "address", name=op.f("pk_coins")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", coinwatch.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("created_at", coinwatch.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_table(
        "strategies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("yaml_config", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", coinwatch.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("updated_at", coinwatch.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_strategies_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_strategies_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategies")),
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chain", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("public_address", sa.String(length=128), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", coinwatch.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chain"], ["chains.id"], name=op.f("fk_wallets_chain_chains")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_wallets_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallets")),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chain", sa.String(length=32), nullable=False),
        sa.Column("coin_address", sa.String(length=128), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("sent_at", coinwatch.db.base.UtcDateTime(timezone=True), nullable=True),
        sa.Column("escalated", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["chain", "coin_address"],
            ["coins.chain", "coins.address"],
            name=op.f("fk_alerts_chain_coins"),
        ),
        sa.ForeignKeyConstraint(["chain"], ["chains.id"], name=op.f("fk_alerts_chain_chains")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_table(
        "bots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chain", sa.String(length=32), nullable=False),
        sa.Column("coin_address", sa.String(length=128), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("paper", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("act_on_inference", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", coinwatch.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chain", "coin_address"],
            ["coins.chain", "coins.address"],
            name=op.f("fk_bots_chain_coins"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_bots_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"], ["strategies.id"], name=op.f("fk_bots_strategy_id_strategies")
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"], ["wallets.id"], name=op.f("fk_bots_wallet_id_wallets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bots")),
    )
    op.create_table(
        "price_alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chain", sa.String(length=32), nullable=False),
        sa.Column("coin_address", sa.String(length=128), nullable=False),
        sa.Column("condition", sa.String(length=255), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chain", "coin_address"],
            ["coins.chain", "coins.address"],
            name=op.f("fk_price_alerts_chain_coins"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_price_alerts_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_alerts")),
    )
    op.create_table(
        "ticks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chain", sa.String(length=32), nullable=False),
        sa.Column("coin_address", sa.String(length=128), nullable=False),
        sa.Column("ts", coinwatch.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("price_native", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("price_usd", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("mcap_usd", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("liquidity_native", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("curve_pct", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("volume_1m", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("volume_5m", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("volume_15m", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("holders", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chain", "coin_address"],
            ["coins.chain", "coins.address"],
            name=op.f("fk_ticks_chain_coins"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticks")),
    )
    with op.batch_alter_table("ticks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_ticks_chain_coin_address_ts", ["chain", "coin_address", "ts"], unique=False
        )

    op.create_table(
        "decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("ts", coinwatch.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("rule", sa.String(length=255), nullable=False),
        sa.Column("outcome", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], name=op.f("fk_decisions_bot_id_bots")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
    )
    op.create_table(
        "positions",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("chain", sa.String(length=32), nullable=False),
        sa.Column("coin_address", sa.String(length=128), nullable=False),
        sa.Column("size", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("cost_native", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("realized_pnl_native", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("updated_at", coinwatch.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], name=op.f("fk_positions_bot_id_bots")),
        sa.ForeignKeyConstraint(
            ["chain", "coin_address"],
            ["coins.chain", "coins.address"],
            name=op.f("fk_positions_chain_coins"),
        ),
        sa.PrimaryKeyConstraint("bot_id", name=op.f("pk_positions")),
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("chain", sa.String(length=32), nullable=False),
        sa.Column("coin_address", sa.String(length=128), nullable=False),
        sa.Column("side", sa.String(length=16), nullable=False),
        sa.Column("amount_native", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("price_native", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("price_usd", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("mcap_usd", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("fee_native", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("price_impact_pct", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("tx_sig", sa.String(length=128), nullable=True),
        sa.Column("paper", sa.Boolean(), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("ts", coinwatch.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], name=op.f("fk_trades_bot_id_bots")),
        sa.ForeignKeyConstraint(
            ["chain", "coin_address"],
            ["coins.chain", "coins.address"],
            name=op.f("fk_trades_chain_coins"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trades")
    op.drop_table("positions")
    op.drop_table("decisions")
    with op.batch_alter_table("ticks", schema=None) as batch_op:
        batch_op.drop_index("ix_ticks_chain_coin_address_ts")

    op.drop_table("ticks")
    op.drop_table("price_alerts")
    op.drop_table("bots")
    op.drop_table("alerts")
    op.drop_table("wallets")
    op.drop_table("strategies")
    op.drop_table("sessions")
    op.drop_table("coins")
    op.drop_table("users")
    op.drop_table("inference_calls")
    op.drop_table("digests")
    op.drop_table("chains")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
